# Generated by Django 5.2.4 on 2025-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_class_location_school_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('jain', 'Jain'), ('buddhist', 'Buddhist'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='blood',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('unmarried', 'Unmarried'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='religion',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('jain', 'Jain'), ('buddhist', 'Buddhist'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
