# Generated by Django 5.2.4 on 2025-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_inactive_date_teacher_inactive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
