# Generated by Django 5.2.4 on 2025-07-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_monthlypayment_code_monthlypayment_end_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='start_year',
        ),
    ]
