# Generated by Django 5.2.4 on 2025-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_monthlypayment_end_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sms_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='total_sms_count',
            field=models.IntegerField(default=0),
        ),
    ]
