# Generated by Django 5.2.4 on 2025-08-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subject_teachingassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingassignment',
            old_name='class_name',
            new_name='student_class',
        ),
    ]
