# Generated by Django 5.2.4 on 2025-08-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_school_location_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
