# Generated by Django 5.2.4 on 2025-08-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_student_user_alter_student_roll_no_examresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='h_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
