# Generated by Django 5.2.4 on 2025-08-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_role_h_name_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='obtained_mark',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_mark',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
