# Generated by Django 5.2.4 on 2025-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_examresult_obtained_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
