# Generated by Django 5.2.4 on 2025-08-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_examresult_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
