# Generated by Django 5.2.4 on 2025-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_examresult_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
