# Generated by Django 5.2.4 on 2025-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_examresult_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='obtained_mark',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_mark',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
